SELECT * from EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM JOBS;
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 50;

UPDATE EMPLOYEES SET SALARY = SALARY * 1.3 WHERE DEPARTMENT_ID = 50;

DELETE FROM EMPLOYEES WHERE EMPLOYEE_ID = 101;

SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' ORDER BY FIRST_NAME;

select count(employee_id) from employees emp where emp.JOB_ID = 'IT_PROG';

SELECT EMPLOYEES.*, dep.DEPARTMENT_NAME FROM EMPLOYEES INNER JOIN DEPARTMENTS DEP ON (EMPLOYEES.DEPARTMENT_ID = DEP.DEPARTMENT_ID) where DEP.DEPARTMENT_ID = 50;

SELECT EMPLOYEES.* FROM EMPLOYEES INNER JOIN DEPARTMENTS DEP ON (EMPLOYEES.DEPARTMENT_ID = DEP.DEPARTMENT_ID) where DEP.LOCATION_ID = 1700;


SELECT sysdate from dual;

select to_char(sysdate, 'dd-MM-yyyy') from dual;

select to_date ('25-11-2014', 'dd-MM-yyyy') from dual;

SELECT UPPER(FIRST_NAME), LOWER(EMAIL) FROM EMPLOYEES;

SELECT CONCAT('First Name: ' , FIRST_NAME) FROM EMPLOYEES;

SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES;

SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES emp WHERE emp.JOB_ID='IT_PROG';

SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = 50;

SELECT MIN(SALARY), MAX(SALARY) FROM EMPLOYEES INNER JOIN DEPARTMENTS DEP ON (EMPLOYEES.DEPARTMENT_ID = DEP.DEPARTMENT_ID) where DEP.LOCATION_ID = 1700;
